// engine/activities.js — Pre-loaded Kaohsiung activity pool + persona profiles

const PERSONAS = [
  {
    id: 'adult',
    name: 'Adult',
    emoji: '👩',
    color: '#9B59B6',
    tagWeights: { shopping: 3, views: 2, food: 1, cultural: 1, nature: 1, indoor: 1 },
    constraints: { maxWalking: 'medium', restRequired: false, maxDuration: 'half-day' }
  },
  {
    id: 'child',
    name: 'Child',
    emoji: '👦',
    color: '#27AE60',
    tagWeights: { dinosaur: 3, 'kid-friendly': 2, interactive: 2, food: 1, indoor: 1 },
    constraints: { maxWalking: 'medium', restRequired: false, maxDuration: '2h' }
  },
  {
    id: 'elderly',
    name: 'Elderly',
    emoji: '👵',
    color: '#E67E22',
    tagWeights: { views: 2, restSpots: 999, food: 1, cultural: 2, shopping: 1, nature: 1, indoor: 2 },
    constraints: { maxWalking: 'low', restRequired: true, maxDuration: '2h' }
  },
  {
    id: 'you',
    name: 'You',
    emoji: '🧒',
    color: '#2980B9',
    tagWeights: { food: 1, views: 1, shopping: 1, cultural: 1, nature: 1, 'kid-friendly': 1, indoor: 1, interactive: 1, dinosaur: 1 },
    constraints: { maxWalking: 'high', restRequired: false, maxDuration: 'full-day' }
  }
];

const ACTIVITIES = [
  {
    id: 'dream-mall',
    name: 'Dream Mall',
    emoji: '🛍️',
    description: 'Largest mall in Taiwan, rooftop amusement park with dinosaur exhibit',
    location: 'Cianjhen District',
    walkingLevel: 'low',
    restSpots: true,
    tags: ['shopping', 'dinosaur', 'indoor', 'kid-friendly', 'interactive'],
    cost: 'medium',
    duration: 'half-day',
    source: 'preloaded'
  },
  {
    id: 'lotus-pond',
    name: 'Lotus Pond',
    emoji: '🌸',
    description: 'Scenic lake with Dragon & Tiger Pagodas, beautiful views, flat walking paths',
    location: 'Zuoying District',
    walkingLevel: 'low',
    restSpots: true,
    tags: ['views', 'cultural', 'nature', 'kid-friendly'],
    cost: 'free',
    duration: '2h',
    source: 'preloaded'
  },
  {
    id: 'liuhe-night-market',
    name: 'Liuhe Night Market',
    emoji: '🍢',
    description: 'Famous night market with street food, seafood, and local snacks',
    location: 'Sinsing District',
    walkingLevel: 'medium',
    restSpots: true,
    tags: ['food', 'shopping', 'cultural'],
    cost: 'low',
    duration: '2h',
    source: 'preloaded'
  },
  {
    id: 'fo-guang-shan',
    name: 'Fo Guang Shan Buddha Museum',
    emoji: '🏛️',
    description: 'Massive Buddhist monastery and museum, peaceful, indoor exhibits, wheelchair-friendly',
    location: 'Dashu District',
    walkingLevel: 'low',
    restSpots: true,
    tags: ['cultural', 'views', 'indoor', 'views'],
    cost: 'free',
    duration: 'half-day',
    source: 'preloaded'
  },
  {
    id: 'pier-2',
    name: 'Pier-2 Art Center',
    emoji: '🎨',
    description: 'Outdoor art space in converted warehouses, murals, installations, cafes',
    location: 'Yancheng District',
    walkingLevel: 'medium',
    restSpots: true,
    tags: ['cultural', 'views', 'interactive', 'kid-friendly'],
    cost: 'free',
    duration: '2h',
    source: 'preloaded'
  },
  {
    id: 'cijin-island',
    name: 'Cijin Island',
    emoji: '🏖️',
    description: 'Ferry ride to island with beach, lighthouse, seafood street, bike rentals',
    location: 'Cijin District',
    walkingLevel: 'high',
    restSpots: true,
    tags: ['nature', 'views', 'food', 'kid-friendly'],
    cost: 'low',
    duration: 'half-day',
    source: 'preloaded'
  },
  {
    id: 'shinkuchan',
    name: 'Shinkuchan Shopping District',
    emoji: '👗',
    description: 'Popular shopping streets with boutiques, accessories, and street food',
    location: 'Sinsing District',
    walkingLevel: 'medium',
    restSpots: true,
    tags: ['shopping', 'food', 'indoor'],
    cost: 'medium',
    duration: '2h',
    source: 'preloaded'
  },
  {
    id: 'shoushan',
    name: 'Shoushan (Monkey Mountain)',
    emoji: '🐒',
    description: 'Hiking trails with wild monkeys, city views, nature reserve',
    location: 'Gushan District',
    walkingLevel: 'high',
    restSpots: false,
    tags: ['nature', 'views', 'interactive', 'kid-friendly'],
    cost: 'free',
    duration: 'half-day',
    source: 'preloaded'
  },
  {
    id: 'kaohsiung-museum-history',
    name: 'Kaohsiung Museum of History',
    emoji: '📜',
    description: 'City history in a Japanese-era building, air-conditioned, seated exhibits',
    location: 'Yancheng District',
    walkingLevel: 'low',
    restSpots: true,
    tags: ['cultural', 'indoor'],
    cost: 'low',
    duration: '2h',
    source: 'preloaded'
  },
  {
    id: 'ruifeng-night-market',
    name: 'Ruifeng Night Market',
    emoji: '🧋',
    description: 'Largest night market in Kaohsiung, boba tea, grilled squid, game stalls',
    location: 'Zuoying District',
    walkingLevel: 'medium',
    restSpots: true,
    tags: ['food', 'shopping', 'kid-friendly', 'interactive'],
    cost: 'low',
    duration: '2h',
    source: 'preloaded'
  },
  {
    id: 'love-river',
    name: 'Love River Cruise',
    emoji: '🛶',
    description: 'Scenic boat ride along Love River, city views, seated, relaxing',
    location: 'Yancheng District',
    walkingLevel: 'low',
    restSpots: true,
    tags: ['views', 'nature'],
    cost: 'low',
    duration: '1h',
    source: 'preloaded'
  },
  {
    id: 'central-park',
    name: 'Central Park',
    emoji: '🌳',
    description: 'Urban park with pond, playground, MRT access, shaded benches',
    location: 'Cianjin District',
    walkingLevel: 'low',
    restSpots: true,
    tags: ['nature', 'kid-friendly', 'views'],
    cost: 'free',
    duration: '1h',
    source: 'preloaded'
  },
  {
    id: 'dome-of-light',
    name: 'Dome of Light',
    emoji: '💫',
    description: 'World\'s largest glass artwork in Formosa Boulevard MRT station, quick visit, indoor',
    location: 'Sinsing District',
    walkingLevel: 'low',
    restSpots: true,
    tags: ['views', 'cultural', 'indoor'],
    cost: 'free',
    duration: '1h',
    source: 'preloaded'
  },
  {
    id: 'kaohsiung-zoo',
    name: 'Kaohsiung Zoo',
    emoji: '🦁',
    description: 'Zoo with dinosaur exhibit area, train ride, shaded paths, benches throughout',
    location: 'Gushan District',
    walkingLevel: 'medium',
    restSpots: true,
    tags: ['dinosaur', 'kid-friendly', 'interactive', 'nature'],
    cost: 'low',
    duration: 'half-day',
    source: 'preloaded'
  },
  {
    id: 'taiwan-sugar-museum',
    name: 'Taiwan Sugar Museum',
    emoji: '🍬',
    description: 'Historic sugar factory turned museum, ice cream, train ride, indoor exhibits',
    location: 'Ciaotou District',
    walkingLevel: 'low',
    restSpots: true,
    tags: ['cultural', 'food', 'indoor', 'kid-friendly', 'interactive'],
    cost: 'low',
    duration: '2h',
    source: 'preloaded'
  },
  {
    id: 'weiwuying',
    name: 'National Kaohsiung Center for the Arts (Weiwuying)',
    emoji: '🏟️',
    description: 'Massive arts complex, outdoor park, indoor performances, stunning architecture',
    location: 'Fengshan District',
    walkingLevel: 'medium',
    restSpots: true,
    tags: ['cultural', 'views', 'indoor'],
    cost: 'medium',
    duration: '2h',
    source: 'preloaded'
  },
  {
    id: 'kaohsiung-main-library',
    name: 'Kaohsiung Main Public Library',
    emoji: '📚',
    description: 'Modern glass library with garden terrace, city views, quiet, air-conditioned',
    location: 'Cianjhen District',
    walkingLevel: 'low',
    restSpots: true,
    tags: ['cultural', 'views', 'indoor'],
    cost: 'free',
    duration: '1h',
    source: 'preloaded'
  },
  {
    id: 'chenqing-lake',
    name: 'Chengcing Lake',
    emoji: '🌊',
    description: 'Scenic reservoir with bridges, pavilions, golf course views, flat paths',
    location: 'Niaosong District',
    walkingLevel: 'medium',
    restSpots: true,
    tags: ['views', 'nature'],
    cost: 'low',
    duration: '2h',
    source: 'preloaded'
  },
  {
    id: 'martyr-shrine',
    name: 'Kaohsiung Martyrs\' Shrine',
    emoji: '⛩️',
    description: 'Traditional Chinese shrine with city views, stairs but manageable, photo spot',
    location: 'Gushan District',
    walkingLevel: 'medium',
    restSpots: true,
    tags: ['cultural', 'views'],
    cost: 'free',
    duration: '1h',
    source: 'preloaded'
  },
  {
    id: 'sanduo-shopping',
    name: 'Sanduo Shopping District',
    emoji: '🏬',
    description: 'Cluster of department stores (SOGO, Shin Kong Mitsukoshi), indoor, air-conditioned',
    location: 'Lingya District',
    walkingLevel: 'low',
    restSpots: true,
    tags: ['shopping', 'indoor', 'food'],
    cost: 'high',
    duration: 'half-day',
    source: 'preloaded'
  },
  {
    id: 'kaohsiung-museum-fine-arts',
    name: 'Kaohsiung Museum of Fine Arts',
    emoji: '🖼️',
    description: 'Fine art exhibitions, sculpture garden outside, indoor galleries, cafe on site',
    location: 'Gushan District',
    walkingLevel: 'low',
    restSpots: true,
    tags: ['cultural', 'indoor', 'views'],
    cost: 'low',
    duration: '2h',
    source: 'preloaded'
  },
  {
    id: 'edaworld',
    name: 'E-DA Theme Park',
    emoji: '🎢',
    description: 'Greek-themed amusement park with mall attached, dinosaur zone, rides for all ages',
    location: 'Dashu District',
    walkingLevel: 'high',
    restSpots: true,
    tags: ['kid-friendly', 'dinosaur', 'interactive', 'shopping'],
    cost: 'high',
    duration: 'full-day',
    source: 'preloaded'
  },
  {
    id: 'sizihwan-bay',
    name: 'Sizihwan Bay',
    emoji: '🌅',
    description: 'Sunset viewing spot, sandy beach area, cafes along the waterfront, gentle paths',
    location: 'Gushan District',
    walkingLevel: 'low',
    restSpots: true,
    tags: ['views', 'nature', 'food'],
    cost: 'free',
    duration: '1h',
    source: 'preloaded'
  },
  {
    id: 'tsoying-old-city',
    name: 'Zuoying Old City Wall',
    emoji: '🏯',
    description: 'Historic Qing dynasty city walls and gates, flat walking, cultural heritage',
    location: 'Zuoying District',
    walkingLevel: 'low',
    restSpots: true,
    tags: ['cultural', 'views', 'nature'],
    cost: 'free',
    duration: '1h',
    source: 'preloaded'
  },
  {
    id: 'kaohsiung-kids-land',
    name: 'Kaohsiung Children\'s Art Park',
    emoji: '🎠',
    description: 'Interactive art playground, sand pits, dinosaur sculptures, shaded, perfect for 5-year-olds',
    location: 'Fengshan District',
    walkingLevel: 'low',
    restSpots: true,
    tags: ['kid-friendly', 'interactive', 'dinosaur', 'nature', 'indoor'],
    cost: 'free',
    duration: '2h',
    source: 'preloaded'
  }
];
